server:
  port: ${PORT:8010}

---
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vineethmaller/springboot-configrepo.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
          search-paths:
          - 'ws_user'
          - 'api_gateway'
          - 'ws_discovery'
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  

management:
  endpoints:
    web:
      exposure:
        include:
        - bus-refresh